// Discovery pages that global search results navigate to.
//
// Search is a discovery feature: a category, specialty, condition or service
// result opens that item's existing marketing page, never the appointment
// booking flow. Every path below is a static <Route> that already exists in
// frontend/src/App.jsx (tests/search/discoveryRoutes.test.js keeps them in
// sync). Paths are only ever looked up here - never built from the request
// or from AI output.

// Specialty pages, keyed by HealthcareCategory.name then
// HealthcareSpecialty.name. Page slugs don't follow the specialty names
// (e.g. OB-GYN, ENT), so each one is listed explicitly, matching the links in
// frontend/src/pages/Specialties.jsx. Specialties without a page (e.g.
// Oncology) fall back to their category page.
const SPECIALTY_DISCOVERY_ROUTES = Object.freeze({
  "General & Everyday Care": {
    "General Physician": "/general-and-everyday-care/general-physician",
    "Internal Medicine": "/general-and-everyday-care/internal-medicine",
    "Family Medicine": "/general-and-everyday-care/family-medicine",
  },
  "Children & Family": {
    "Adolescent Care": "/child-and-family-care/adolescent-medicine",
    Pediatrics: "/child-and-family-care/pediatrics",
  },
  "Mental Health": {
    Psychiatry: "/mental-health/psychiatry",
    "Psychology / Counselling": "/mental-health/psychology-counseling",
    "Behavioral Health": "/mental-health/behavioral-health",
  },
  "Skin & Hair": {
    Dermatology: "/skin-and-hair-care/dermatology",
  },
  "Women's Health": {
    "OB-GYN": "/women-health/obstetrics-and-gynaecology",
    "Menopause Care": "/women-health/menopause-care",
    "Women's Mental Health": "/women-health/women-mental-health",
    "Lactation Consulting": "/women-health/lactation-consulting",
  },
  "Men's Health": {
    "Men's Health": "/mens-health/men-health",
    Urology: "/mens-health/urology",
  },
  "Weight & Nutrition": {
    "Weight Management": "/weight-and-nurtrition/weight-management",
    "Nutrition & Dietetics": "/weight-and-nurtrition/nutrition-and-dietetics",
    "Lifestyle Medicine": "/weight-and-nurtrition/lifestyle-medicine",
  },
  "Chronic Care & Expert Opinion": {
    Cardiology: "/chronic-care/cardiology",
    Neurology: "/chronic-care/neurology",
    Endocrinology: "/chronic-care/endocrinology",
    Gastroenterology: "/chronic-care/gastroenterology",
    Pulmonology: "/chronic-care/pulmonology",
    // Specialties.jsx links "/export-medical-opinion" (no such route); this is
    // the route that renders the ExpertMedicalOpinion specialty page.
    "Expert Medical Opinion": "/expert-medical-opinion",
  },
  "Eye, Ear & Bone": {
    Ophthalmology: "/eye-ear-bone/ophthalmology",
    ENT: "/eye-ear-bone/ear-nose-throat",
    Orthopedics: "/eye-ear-bone/orthopedics",
  },
  "Sexual Health": {
    "Sexual Health": "/sexual-health/sexual-health-and-wellness",
  },
  "Travel & Global Care": {
    "Travel Medicine": "/travel-and-global-care/travel-medicine",
    "Global / Cross-Border Care": "/travel-and-global-care/global-cross-border-care",
  },
});

// Condition and service pages (the "condition pages" block of App.jsx).
const CONDITION_DISCOVERY_ROUTES = new Set([
  "/allergic-rhinitis",
  "/asthma-flare-up",
  "/athletes-foot",
  "/bronchitis",
  "/burning-urination",
  "/burnout",
  "/cellulitis",
  "/child-and-family-care/adolescent-medicine/mood-anxiety-teens",
  "/child-and-family-care/adolescent-medicine/puberty-concerns",
  "/child-and-family-care/adolescent-medicine/sports-injuries",
  "/child-and-family-care/pediatrics/ear-pain-children",
  "/child-and-family-care/pediatrics/feeding-concerns",
  "/child-and-family-care/pediatrics/pediatric-cold-flu",
  "/child-and-family-care/pediatrics/pediatric-fever",
  "/child-and-family-care/pediatrics/skin-rash-in-children",
  "/childhood-allergies",
  "/chronic-care/cardiology/chest-pain",
  "/chronic-care/cardiology/heart-disease-follow-up",
  "/chronic-care/cardiology/high-blood-pressure",
  "/chronic-care/cardiology/high-cholesterol",
  "/chronic-care/cardiology/palpitations",
  "/chronic-care/cardiology/pre-op-cardiac-clearance",
  "/chronic-care/endocrinology/hormone-imbalance",
  "/chronic-care/endocrinology/osteoporosis",
  "/chronic-care/endocrinology/thyroid-disorders",
  "/chronic-care/endocrinology/type-2-diabetes",
  "/chronic-care/gastroenterology/abdominal-pain",
  "/chronic-care/gastroenterology/acid-reflux-gerd",
  "/chronic-care/gastroenterology/bloating",
  "/chronic-care/gastroenterology/constipation",
  "/chronic-care/gastroenterology/fatty-liver",
  "/chronic-care/gastroenterology/irritable-bowel-syndrome",
  "/chronic-care/neurology/chronic-migraine",
  "/chronic-care/neurology/dizziness",
  "/chronic-care/neurology/memory-concerns",
  "/chronic-care/neurology/migraine",
  "/chronic-care/neurology/numbness-and-tingling",
  "/chronic-care/neurology/seizures-epilepsy-follow-up",
  "/chronic-care/neurology/tremor",
  "/chronic-care/pulmonology/asthma",
  "/chronic-care/pulmonology/copd",
  "/chronic-care/pulmonology/persistent-cough",
  "/chronic-care/pulmonology/post-covid-concerns",
  "/chronic-care/pulmonology/shortness-of-breath",
  "/chronic-care/pulmonology/sleep-apnea-screening",
  "/chronic-kidney-disease",
  "/chronic-medication-management",
  "/contact-dermatitis",
  "/covid-19",
  "/dehydration",
  "/diarrhea",
  "/doctors-note",
  "/emergency-contraception-guidance",
  "/emergency-teleconsultation-abroad",
  "/eye-ear-bone/ear-nose-throat/ear-infection",
  "/eye-ear-bone/ear-nose-throat/ear-pain",
  "/eye-ear-bone/ear-nose-throat/hoarseness",
  "/eye-ear-bone/ear-nose-throat/nasal-congestion",
  "/eye-ear-bone/ear-nose-throat/sore-throat",
  "/eye-ear-bone/ear-nose-throat/tonsillitis",
  "/eye-ear-bone/ear-nose-throat/vertigo",
  "/eye-ear-bone/ophthalmology/dry-eyes",
  "/eye-ear-bone/ophthalmology/eye-irritation",
  "/eye-ear-bone/ophthalmology/eye-redness",
  "/eye-ear-bone/ophthalmology/eye-strain",
  "/eye-ear-bone/ophthalmology/stye",
  "/eye-ear-bone/ophthalmology/vision-changes",
  "/eye-ear-bone/orthopedics/arthritis",
  "/eye-ear-bone/orthopedics/back-pain",
  "/eye-ear-bone/orthopedics/knee-pain",
  "/eye-ear-bone/orthopedics/muscle-strain",
  "/eye-ear-bone/orthopedics/neck-pain",
  "/eye-ear-bone/orthopedics/osteoarthritis",
  "/fitness-travel-evaluation",
  "/follow-up-consultation",
  "/food-poisoning",
  "/frequent-urination",
  "/gastritis",
  "/general-and-everyday-care/family-medicine/routine-check-ups",
  "/general-and-everyday-care/family-medicine/vaccination-advice",
  "/general-and-everyday-care/family-medicine/whole-family-illnesses",
  "/general-and-everyday-care/general-physician/body-aches",
  "/general-and-everyday-care/general-physician/cold-and-flu",
  "/general-and-everyday-care/general-physician/cough",
  "/general-and-everyday-care/general-physician/fatigue",
  "/general-and-everyday-care/general-physician/fever",
  "/general-and-everyday-care/general-physician/headache",
  "/general-and-everyday-care/general-physician/minor-infections",
  "/general-and-everyday-care/general-physician/nausea-and-vomiting",
  "/general-and-everyday-care/general-physician/pink-eye",
  "/general-and-everyday-care/general-physician/sinus-infection",
  "/general-and-everyday-care/internal-medicine/medication-review",
  "/general-and-everyday-care/internal-medicine/multi-system-complaints",
  "/general-and-everyday-care/internal-medicine/preventive-screening",
  "/general-and-everyday-care/internal-medicine/undiagnosed-symptoms",
  "/genital-itching",
  "/genital-rash",
  "/glp-program-eligibility",
  "/growth-development",
  "/heavy-periods",
  "/hemorrhoids",
  "/indigestion",
  "/insect-bite",
  "/itchy-skin",
  "/jet-lag",
  "/joint-pain",
  "/lab-results-review",
  "/medical-certificate",
  "/mens-health/men-health/erectile-dysfunction",
  "/mens-health/men-health/hair-loss",
  "/mens-health/men-health/low-libido",
  "/mens-health/men-health/low-testosterone-symptoms",
  "/mens-health/men-health/prostate-health",
  "/mens-health/urology/bladder-problems",
  "/mens-health/urology/blood-in-urine",
  "/mens-health/urology/kidney-stones",
  "/mens-health/urology/urinary-incontinence",
  "/urinary-tract-infection",
  "/mens-wellness-consultation",
  "/mental-health/behavioral-health/adjustment-difficulties",
  "/mental-health/behavioral-health/anger-management",
  "/mental-health/behavioral-health/sleep-related-anxiety",
  "/mental-health/behavioral-health/substance-use-support",
  "/mental-health/psychiatry/Ocd",
  "/mental-health/psychiatry/adhd-evaluation",
  "/mental-health/psychiatry/anxiety",
  "/mental-health/psychiatry/bipolar-disorder-follow-up",
  "/mental-health/psychiatry/depression",
  "/mental-health/psychiatry/insomnia",
  "/mental-health/psychiatry/panic-attacks",
  "/mental-health/psychiatry/ptsd",
  "/mental-health/psychology-counseling/grief-and-loss",
  "/mental-health/psychology-counseling/low-self-esteem",
  "/mental-health/psychology-counseling/relationship-stress",
  "/mental-health/psychology-counseling/stress",
  "/mental-health/psychology-counseling/trauma-support",
  "/metabolic-syndrome",
  "/mild-asthma-symptoms",
  "/minor-burns",
  "/motion-sickness",
  "/online-second-medical-opinion/cancer-second-opinion",
  "/online-second-medical-opinion/complex-diagnosis-review",
  "/online-second-medical-opinion/surgery-second-opinion",
  "/online-second-medical-opinion/treatment-plan-review",
  "/pink-eye-children",
  "/pneumonia-follow-up",
  "/postpartum-concerns",
  "/pregnancy-related-questions",
  "/premature-ejaculation",
  "/prescription-refill",
  "/return-to-work-clearance",
  "/rheumatoid-arthritis",
  "/ringworm",
  "/seasonal-allergies",
  "/second-medical-opinion",
  "/sexual-health/sexual-health-and-wellness/chlamydia",
  "/sexual-health/sexual-health-and-wellness/gonorrhea",
  "/sexual-health/sexual-health-and-wellness/herpes",
  "/sexual-health/sexual-health-and-wellness/hiv-prevention-guidance",
  "/sexual-health/sexual-health-and-wellness/partner-exposure-concerns",
  "/sexual-health/sexual-health-and-wellness/safe-sex-counseling",
  "/sexual-health/sexual-health-and-wellness/sti-consultation",
  "/shingles",
  "/skin-and-hair-care/dermatology/acne",
  "/skin-and-hair-care/dermatology/cold-sores",
  "/skin-and-hair-care/dermatology/eczema",
  "/skin-and-hair-care/dermatology/fungal-skin-infection",
  "/skin-and-hair-care/dermatology/hair-loss",
  "/skin-and-hair-care/dermatology/hives",
  "/skin-and-hair-care/dermatology/mole-skin-checks",
  "/skin-and-hair-care/dermatology/nail-problems",
  "/skin-and-hair-care/dermatology/psoriasis",
  "/skin-and-hair-care/dermatology/rosacea",
  "/skin-and-hair-care/dermatology/skin-rash",
  "/skin-and-hair-care/dermatology/warts",
  "/sore-throat-children",
  "/specialist-referral",
  "/stomach-pain-children",
  "/strep-throat",
  "/swollen-feet-ankles",
  "/travel-and-global-care/global-cross-border-care/cross-border-consultation",
  "/travel-and-global-care/global-cross-border-care/international-medical-assistance",
  "/travel-and-global-care/global-cross-border-care/medication-refill-while-traveling",
  "/travel-and-global-care/global-cross-border-care/referral-coordination-overseas",
  "/travel-and-global-care/travel-medicine/altitude-sickness",
  "/travel-and-global-care/travel-medicine/food-poisoning-while-traveling",
  "/travel-and-global-care/travel-medicine/malaria-prevention",
  "/travel-and-global-care/travel-medicine/post-travel-symptoms",
  "/travel-and-global-care/travel-medicine/pre-travel-vaccinations",
  "/travel-and-global-care/travel-medicine/travel-related-fever",
  "/travel-and-global-care/travel-medicine/travelers-diarrhea",
  "/travel-medical-certification",
  "/upper-respiratory-infection",
  "/urinary-symptoms-in-men",
  "/vomiting",
  "/vomiting-diarrhea-children",
  "/weight-and-nurtrition/lifestyle-medicine/diet-and-exercise-planning",
  "/weight-and-nurtrition/lifestyle-medicine/healthy-habit-coaching",
  "/weight-and-nurtrition/lifestyle-medicine/sleep-hygiene",
  "/weight-and-nurtrition/nutrition-and-dietetics/cholesterol-lowering-diet",
  "/weight-and-nurtrition/nutrition-and-dietetics/diabetic-diet",
  "/weight-and-nurtrition/nutrition-and-dietetics/food-intolerance-planning",
  "/weight-and-nurtrition/nutrition-and-dietetics/pregnancy-nutrition",
  "/weight-and-nurtrition/nutrition-and-dietetics/sports-nutrition",
  "/weight-and-nurtrition/weight-management/binge-eating",
  "/weight-and-nurtrition/weight-management/obesity",
  "/weight-and-nurtrition/weight-management/weight-loss-planning",
  "/wheezing",
  "/women-health/lactation-consulting/latch-problems",
  "/women-health/lactation-consulting/low-milk-supply",
  "/women-health/lactation-consulting/nipple-pain",
  "/women-health/lactation-consulting/weaning-guidance",
  "/women-health/menopause-care/hot-flashes",
  "/women-health/menopause-care/hrt-guidance",
  "/women-health/obstetrics-and-gynaecology/bacterial-vaginosis",
  "/women-health/obstetrics-and-gynaecology/birth-control",
  "/women-health/obstetrics-and-gynaecology/fertility-concerns",
  "/women-health/obstetrics-and-gynaecology/irregular-periods",
  "/women-health/obstetrics-and-gynaecology/menstrual-cramps",
  "/women-health/obstetrics-and-gynaecology/pcos",
  "/women-health/obstetrics-and-gynaecology/pelvic-pain",
  "/women-health/obstetrics-and-gynaecology/prenatal-consultation",
  "/women-health/obstetrics-and-gynaecology/vaginal-yeast-infection",
  "/women-health/women-mental-health/perinatal-anxiety",
  "/women-health/women-mental-health/pmdd",
  "/women-health/women-mental-health/postnatal-depression",
]);

// Generic listing pages, used when an item has no dedicated page.
const DISCOVERY_FALLBACK_ROUTES = Object.freeze({
  category: "/categories",
  specialty: "/specialties",
  condition: "/conditions",
});

module.exports = {
  SPECIALTY_DISCOVERY_ROUTES,
  CONDITION_DISCOVERY_ROUTES,
  DISCOVERY_FALLBACK_ROUTES,
};
