const Payment = require("../models/Payment");
const User = require("../models/User");
const { recordPaymentAndInvoice } = require("../utils/billing");

// Give the original fire-and-forget attempt (triggered right after a
// booking succeeds — see appointmentController.js / CategoryConsultationController.js)
// time to finish before a payment is considered "stuck". Without this, the
// sweep could pick up a payment whose invoice is still being generated by
// the original call and kick off a redundant concurrent attempt.
const GRACE_PERIOD_MS = 3 * 60 * 1000;

// Stop auto-retrying a payment that keeps failing (e.g. a persistently
// misconfigured S3 bucket) — beyond this it's logged loudly for manual
// follow-up instead of being retried forever.
const MAX_ATTEMPTS = 6;

// Cap per sweep so a large backlog can't hammer S3/SMTP all at once; the
// next interval picks up whatever's left.
const BATCH_SIZE = 20;

// In-process mutex: if a sweep is still processing its batch when the next
// interval fires (e.g. slow S3), skip the overlapping run rather than
// letting two sweeps race the same stale payments.
let isRunning = false;

// Finds Payment records whose invoice generation never completed
// (payment.invoice is still null) and safely retries it. Never touches a
// Payment that already has an invoice, and never creates a duplicate
// Payment or Invoice — see the idempotency guards in billing.js, which this
// reuses via recordPaymentAndInvoice/generateInvoiceForPayment.
async function runInvoiceReconciliation() {
  if (isRunning) return { skipped: true };
  isRunning = true;

  const result = { scanned: 0, recovered: 0, failed: 0, exhausted: 0 };
  try {
    const cutoff = new Date(Date.now() - GRACE_PERIOD_MS);
    const stalePayments = await Payment.find({
      invoice: null,
      createdAt: { $lt: cutoff },
      invoiceAttempts: { $lt: MAX_ATTEMPTS },
    })
      .sort({ createdAt: 1 })
      .limit(BATCH_SIZE)
      .lean();

    result.scanned = stalePayments.length;

    for (const payment of stalePayments) {
      try {
        const user = await User.findById(payment.user).select("name email").lean();

        // Re-derives the same call that originally recorded this payment.
        // Payment.create() inside recordPaymentAndInvoice will hit the
        // unique (gateway, gatewayReference) index and fail with E11000
        // (this payment already exists), which recordPaymentAndInvoice
        // already handles by re-fetching the existing row — so this can
        // never create a second Payment. It then retries invoice
        // generation via the same idempotent path used everywhere else.
        await recordPaymentAndInvoice({
          userId: payment.user,
          userName: user?.name,
          userEmail: user?.email,
          appointmentId: payment.appointment,
          categoryConsultationId: payment.categoryConsultation,
          gateway: payment.gateway,
          gatewayReference: payment.gatewayReference,
          amountCents: payment.amountCents,
          currency: payment.currency,
          description: payment.description,
        });

        result.recovered += 1;
      } catch (err) {
        result.failed += 1;
        const attempts = (payment.invoiceAttempts || 0) + 1;
        if (attempts >= MAX_ATTEMPTS) {
          result.exhausted += 1;
          console.error(
            `[invoice-reconcile] Payment ${payment._id} has failed invoice generation ${attempts} time(s) and will no longer be auto-retried. Needs manual investigation. Last error: ${err.message}`
          );
        } else {
          console.error(
            `[invoice-reconcile] Retry ${attempts}/${MAX_ATTEMPTS} failed for payment ${payment._id}:`,
            err.message
          );
        }
      }
    }
  } finally {
    isRunning = false;
  }

  if (result.scanned > 0) {
    console.log(
      `[invoice-reconcile] scanned=${result.scanned} recovered=${result.recovered} failed=${result.failed} exhausted=${result.exhausted}`
    );
  }

  return result;
}

function scheduleInvoiceReconciliation() {
  const intervalMs = Number(process.env.INVOICE_RECONCILE_INTERVAL_MS) || 15 * 60 * 1000;
  setInterval(() => {
    runInvoiceReconciliation().catch((err) => console.error("invoice reconciliation error:", err));
  }, intervalMs).unref();
}

module.exports = { runInvoiceReconciliation, scheduleInvoiceReconciliation };
