const mongoose = require("mongoose");
const { analyzeForAnalytics } = require("../services/search/queryRedaction");
const {
  analyticsSchemaOptions,
  SCHEMA_VERSION,
  SETTLED_BY,
  AI_STATUSES,
  OUTCOMES,
  RESULT_TYPES,
  MAX_RESULTS_TOTAL,
  MAX_TERM_LENGTH,
  MAX_PATH_LENGTH,
  UUID_V4,
  SAFE_PATH,
} = require("../services/searchAnalytics/constants");

// One meaningful, settled search (not one keystroke): the privacy-checked
// search term plus what the search found. Standalone collection - it has no
// references to users, patients, doctors, appointments, consultations or
// taxonomy records, and by design carries no ip, user agent, session or
// account data. Written only by services/searchAnalytics/recorder.js.
//
// Doctors are never stored: an interaction involving a doctor result is
// dropped before it gets here, so "doctor" is not an allowed result type.
const STORED_TYPES = RESULT_TYPES.filter((type) => type !== "doctor");

const searchInteractionSchema = new mongoose.Schema(
  {
    // Random per search episode (generated by the browser); not tied to a person.
    interactionId: { type: String, required: true, match: UUID_V4 },
    // Normalised search text; an event whose text trips a privacy rule is never stored.
    term: {
      type: String,
      required: true,
      minlength: 2,
      maxlength: MAX_TERM_LENGTH,
      validate: [
        { validator: (v) => !/[\u0000-\u001f\u007f]/.test(v), message: "term has control characters" },
        { validator: (v) => analyzeForAnalytics(v).store === true, message: "term failed the privacy check" },
      ],
    },
    // Grouping key: singular form of the match-normalised term.
    termKey: { type: String, required: true, maxlength: MAX_TERM_LENGTH, match: /^[a-z0-9]+(?: [a-z0-9]+)*$/ },
    settledBy: { type: String, required: true, enum: SETTLED_BY },
    aiStatus: { type: String, required: true, enum: AI_STATUSES },
    resultCount: {
      type: Number,
      required: true,
      min: 0,
      max: MAX_RESULTS_TOTAL,
      validate: { validator: Number.isInteger, message: "resultCount must be an integer" },
    },
    resultTypes: {
      type: [{ type: String, enum: STORED_TYPES }],
      default: [],
      validate: {
        validator: (v) => v.length <= STORED_TYPES.length && new Set(v).size === v.length,
        message: "resultTypes must be unique",
      },
    },
    outcome: { type: String, required: true, enum: OUTCOMES },
    dedicatedPageAvailable: { type: Boolean, required: true },
    topResultType: { type: String, enum: [...STORED_TYPES, null], default: null },
    topResultPath: {
      type: String,
      default: null,
      maxlength: MAX_PATH_LENGTH,
      validate: { validator: (v) => v === null || SAFE_PATH.test(v), message: "topResultPath must be a plain site path" },
    },
    topResultDedicated: { type: Boolean, default: null },
    topScore: { type: Number, default: null, min: 0, max: 100 },
    schemaVersion: { type: Number, required: true, default: SCHEMA_VERSION },
    // First recorded + 90 days; the TTL index below removes the document.
    expiresAt: { type: Date, required: true },
  },
  { collection: "searchinteractions", strict: "throw", versionKey: false, timestamps: true, ...analyticsSchemaOptions() },
);

// Cross-field rules, so an inconsistent document can never be stored. They are
// path validators (not pre("validate") middleware) so that every validation
// entry point enforces them; the recorder uses awaited document.validate().
searchInteractionSchema.path("outcome").validate(function outcomeMatchesCount(value) {
  return (value === "no_results") === (this.resultCount === 0);
}, "outcome must match resultCount");
searchInteractionSchema.path("resultCount").validate(function emptyHasNoDetails(value) {
  if (value !== 0) return true;
  return !(this.resultTypes.length || this.topResultType || this.topResultPath || this.dedicatedPageAvailable);
}, "empty results cannot carry result details");
searchInteractionSchema.path("resultTypes").validate(function resultsNeedTypes(value) {
  return this.resultCount === 0 || value.length > 0;
}, "results require resultTypes");
searchInteractionSchema.path("dedicatedPageAvailable").validate(function dedicatedNeedsPage(value) {
  return this.outcome !== "dedicated_page_found" || value === true;
}, "dedicated outcome requires a dedicated page");
searchInteractionSchema.path("aiStatus").validate(function aiMatchesSettlement(value) {
  // Only non-submit events (no AI involved) are "not_requested".
  return (this.settledBy === "submit") !== (value === "not_requested");
}, "aiStatus must match how the interaction settled");

// Dedupe / upsert key.
searchInteractionSchema.index({ interactionId: 1 }, { unique: true });
// 90-day raw retention (expireAfterSeconds counts from expiresAt itself).
searchInteractionSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
// Date windows and the (later) daily rollup scan.
searchInteractionSchema.index({ createdAt: -1 });
// Gap / opportunity reports: filter by outcome within a window.
searchInteractionSchema.index({ outcome: 1, createdAt: -1 });
// Grouping and trend by normalised term.
searchInteractionSchema.index({ termKey: 1, createdAt: -1 });

const SearchInteraction = mongoose.model("SearchInteraction", searchInteractionSchema);

module.exports = SearchInteraction;
